#!/usr/bin/bash
err="\033[1;31m"
n="\033[0m"

Del(){
clear
echo "[1] Vmess"
echo "[2] Vless"
echo "[x] Exit"
read -p $'\n[Choose] > ' del
if [[ ${del} == 1 ]]; then
noc=`grep -c -E "^### " "/etc/v2ray/config.json"`
if [[ ${noc} == '0' ]]; then
	echo -e "${err}You have no existing clients!${n}"
	exit
fi
clear
echo "Select the existing client you want to remove!"
echo "=============================================="
grep -E "^### " "/etc/v2ray/config.json" | cut -d ' ' -f 2-3 | nl -s ') '
echo "=============================================="
until [[ ${cn} -ge 1 && ${cn} -le ${noc} ]]; do
	if [[ ${cn} == '1' ]]; then
		read -p "Select client [1]: " cn
	else
		read -p "Select client [1-${noc}]: " cn
	fi
done
user=$(grep -E "^### " "/etc/v2ray/config.json" | cut -d ' ' -f 2 | sed -n "${cn}"p)
exp=$(grep -E "^### " "/etc/v2ray/config.json" | cut -d ' ' -f 3 | sed -n "${cn}"p)
sed -i "/^### ${user} ${exp}/,/^},{/d" /etc/v2ray/config.json
rm -f /etc/v2ray/${user}.json
clear
echo "Successfully delete VMESS Account"
echo "================================="
echo "Username  : ${user}"
echo "Expired   : ${exp}"
echo "================================="
systemctl restart v2ray

elif [[ ${del} == 2 ]]; then
noc=`grep -c -E "^### " "/etc/xray/config.json"`
if [[ ${noc} == '0' ]]; then
	echo -e "${err}You have no existing clients!${n}"
	exit
fi
clear
echo "Select the existing client you want to remove!"
echo "=============================================="
grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') '
echo "=============================================="
until [[ ${cn} -ge 1 && ${cn} -le ${noc} ]]; do
	if [[ ${cn} == '1' ]]; then
		read -p "Select client [1]: " cn
	else
		read -p "Select client [1-${noc}]: " cn
	fi
done
user=$(grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${cn}"p)
exp=$(grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${cn}"p)
sed -i "/^### ${user} ${exp}/,/^},{/d" /etc/xray/config.json
clear
echo "Successfully delete VLESS Account"
echo "================================="
echo "Username  : ${user}"
echo "Expired   : ${exp}"
echo "================================="
systemctl restart xray

elif [[ ${del} == x ]]; then
exit

else
Del

fi
}

Del